# Generated by Django 4.0.4 on 2022-06-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.IntegerField()),
                ('Address1', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.profile')),
            ],
        ),
    ]
